name: ZBoard
version: '${project.version}'
main: pureen.zboard.ZBoard
api-version: '1.20'
softdepend:
  - BetonQuest
commands:
  checkboarddata:
      description: Use for seeing saved data in playersdata.yml
  zboard:
      description: General ZBoard command
